FlightReservationSystem/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
//using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlightReservationSystem.Models;

namespace FlightReservationSystem.Controllers
{
    [Authorize(Users = "admin@frs.com")]
    public class FlightsController : Controller
    {
        private FlightReservationSystemContext db = new FlightReservationSystemContext();

        // GET: Flights
        public ActionResult Index()
        {
            return View(db.Flight.ToList());
        }

        // GET: Flights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // GET: Flights/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "flightId,flightName,seatFirstclass,seatBusinessclass,seatEconomyclass")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                db.Flight.Add(flight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(flight);
        }

        // GET: Flights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "flightId,flightName,seatFirstclass,seatBusinessclass,seatEconomyclass")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flight flight = db.Flight.Find(id);
            db.Flight.Remove(flight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlightReservationSystem/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
//using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlightReservationSystem.Models;
using System.Configuration;
using System.Data.SqlClient;

namespace FlightReservationSystem.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private FlightReservationSystemContext db = new FlightReservationSystemContext();

        // GET: Reservations
        public ActionResult Index()
        {
            var ticket = db.Ticket.Include(t => t.Flight).Include(t => t.Payment).Include(t => t.Schedule).Where(t => t.UserId == User.Identity.Name);
            return View(ticket.ToList());
        }

        //GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Ticket.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        // POST: Reservations/Book
        public ActionResult Book(int sid, int fid, DateTime doj, string name, string Tclass)
        {

            Ticket model = new Ticket()
            {
                flightId = fid,
                scheduleId = sid,
                dateOfJourney = doj.Date,
                travelclass = Tclass
                //UserId = User.Identity.Name
            };
            ViewBag.flightname = name;

            return View(model);
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CompleteBooking([Bind(Include = "paymentMode,totalAmount,bankDetails")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                db.Payment.Add(payment);
                db.SaveChanges();
            }

            Ticket ticket = TempData["Ticket"] as Ticket;
            ticket.UserId = User.Identity.Name;
            ticket.paymentId = payment.paymentId;

            db.Ticket.Add(ticket);
            db.SaveChanges();

            Schedule schedule = db.Schedule.Find(ticket.scheduleId);
            if (ticket.travelclass.Contains("First"))
            {
                schedule.FCseats--;
            }
            else if (ticket.travelclass.Contains("Business"))
            {
                schedule.BCseats--;
            }
            else
            {
                schedule.ECseats--;
            }
            db.Entry(schedule).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Payment([Bind(Include = "flightId,scheduleId,dateOfJourney,passengerName,gender,phoneNumber,address,emergencyContact,travelclass")] Ticket ticket)
        {
            TempData["Ticket"] = ticket;
            //if (ticket.travelclass.Contains("First")) {
            //    //int noOfseats = db.Flight.Include(f => f.seatFirstclass)
            //    //                        .Where(f => f.flightId == ticket.flightId).Count();

            //}
            //else if (ticket.travelclass.Contains("First")) { 
            //    int noOfseats = db.Flight.Include(f => f.seatBusinessclass)
            //                            .Where(f => f.flightId == ticket.flightId).Count();
            //}
            //else
            //{
            //     int noOfseats = db.Flight.Include(f => f.seatEconomyclass)
            //                            .Where(f => f.flightId == ticket.flightId).Count();
            //}

            ticket.seatNo = db.Ticket.Include(t => t.ticketId).Where(t => t.travelclass == ticket.travelclass).Count() + 1;
            Payment payment = new Payment()
            {
                totalAmount = getcostofticket(ticket.scheduleId, ticket.travelclass)
            };

            return View(payment);
        }

        private double getcostofticket(int scheduleId,string travelclass)
        {
            double cost=0.00;
            Schedule s = new Schedule();
            var query= "SELECT cost"+travelclass+" FROM Schedule where scheduleId=" + scheduleId;
            string cString = ConfigurationManager.ConnectionStrings["FlightReservationSystemContext"].ConnectionString;
            //string cString = "Data Source=(LocalDb)\\MSSQLLocalDB;Initial Catalog = aspnet-FlightReservationSystem-20151101020301; Integrated Security = True";
            using (SqlConnection c = new SqlConnection(cString))
            {
                c.Open();
                using (SqlCommand cmd = new SqlCommand(query, c))
                {
                    using (SqlDataReader rdr = cmd.ExecuteReader())
                    {
                        while (rdr.Read())
                        {
                            cost = rdr.GetDouble(rdr.GetOrdinal("cost" + travelclass));
                        }
                    }
                }
            }
            return (cost);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Ticket.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ViewBag.flightId = new SelectList(db.Flight, "flightId", "flightName", ticket.flightId);
            ViewBag.paymentId = new SelectList(db.Payment, "paymentId", "paymentMode", ticket.paymentId);
            ViewBag.scheduleId = new SelectList(db.Schedule, "scheduleId", "source", ticket.scheduleId);
            return View(ticket);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ticketId,UserId,flightId,scheduleId,paymentId,dateOfJourney,seatNo,passengerName,phoneNumber,address,emergencyContact,travelclass")] Ticket ticket)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(ticket).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.flightId = new SelectList(db.Flight, "flightId", "flightName", ticket.flightId);
        //    ViewBag.paymentId = new SelectList(db.Payment, "paymentId", "paymentMode", ticket.paymentId);
        //    ViewBag.scheduleId = new SelectList(db.Schedule, "scheduleId", "source", ticket.scheduleId);
        //    return View(ticket);
        //}

        // GET: Reservations/Delete/5
        public ActionResult CancelTicket(int id)
        {
            
            Ticket ticket = db.Ticket.Find(id);
            //ViewBag.cancelexception = "true";
            //if (ticket.dateOfJourney.CompareTo(DateTime.Today) > 0)
            //{
            //    ViewBag.cancelexception = "false";
            //}
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("CancelTicket")]
        [ValidateAntiForgeryToken]
        public ActionResult CancelConfirmed(int id)
        {
            Ticket ticket = db.Ticket.Find(id);
            db.Ticket.Remove(ticket);
            db.SaveChanges();
            Schedule schedule = db.Schedule.Find(ticket.scheduleId);
            if (ticket.travelclass.Contains("First"))
            {
                schedule.FCseats++;
            }
            else if (ticket.travelclass.Contains("Business"))
            {
                schedule.BCseats++;
            }
            else
            {
                schedule.ECseats++;
            }
            db.Entry(schedule).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlightReservationSystem/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
//using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlightReservationSystem.Models;

namespace FlightReservationSystem.Controllers
{
    public class SchedulesController : Controller
    {
        private FlightReservationSystemContext db = new FlightReservationSystemContext();

        // GET: Schedules
        public ActionResult Index()
        {
            var schedule = db.Schedule.Include(s => s.Flight);
            return View(schedule.ToList());
        }

        // GET: Schedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedule.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // GET: Schedules/Create
        public ActionResult Create()
        {
            ViewBag.flightId = new SelectList(db.Flight, "flightId", "flightName");
            return View();
        }

        // POST: Schedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "scheduleId,flightId,source,sourceId,dest,destId,scheduleDate,depatureTime,arrivalDate,arrivalTime,status,costFirst,costBusiness,costEconomy,traveltype")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                db.Schedule.Add(schedule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.flightId = new SelectList(db.Flight, "flightId", "flightName", schedule.flightId);
            return View(schedule);
        }

        // GET: Schedules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedule.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.flightId = new SelectList(db.Flight, "flightId", "flightName", schedule.flightId);
            return View(schedule);
        }

        // POST: Schedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "scheduleId,flightId,source,sourceId,dest,destId,scheduleDate,depatureTime,arrivalDate,arrivalTime,status,costFirst,costBusiness,costEconomy,traveltype")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(schedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.flightId = new SelectList(db.Flight, "flightId", "flightName", schedule.flightId);
            return View(schedule);
        }

        // GET: Schedules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedule.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Schedule schedule = db.Schedule.Find(id);
            db.Schedule.Remove(schedule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlightReservationSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>Flight Reservation System</h3>

<p>

Users will be able to look for, book and cancel flights. There are 3 different
types of users. The administrator will be able to add/delete destinations, change prices and so on. The

registered users will be able to book/cancel flights. Finally, the guests will be able to search for flights,

but they won't be able to reserve them unless they register.</p>

FlightReservationSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<div>
    Site Administration:
        Group 2
</div>
<br/>

<address>
    <strong>Email Id:</strong>   <a href="mailto:sushmitha.miriam@gmail.com">sushmitha.miriam@gmail.com</a><br />
</address>

FlightReservationSystem/Views/Home/Index.cshtml
@model FlightReservationSystem.Models.Schedule
@{
    ViewBag.Title = "Home Page";
}


<div class="jumbotron">
    <h2>Flight Reservation System</h2>
    <p class="lead">Book Flights for lowest costs and enjoy your journey</p>
</div>

@if (User.Identity.Name.Contains("admin@frs.com"))
{
    <h5>
        @Html.ActionLink("Modify Schedule", "Index", "Schedules") <br />
        @Html.ActionLink("Modify flights Information", "Index", "Flights")
    </h5>

}
<div class="row">
    <div class="col-md-6">
        <h4>Search for flights:</h4>
        <br />
        @using (Html.BeginForm("SearchResults", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <fieldset>
                <div class="form-group">
                    <label class="col-md-2">Source: </label>
                    <div class="col-md-10">
                        @Html.DropDownList("source", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.source, "", new { @class = "text-danger" })
                        <br />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2">Destination: </label>
                    <div class="col-md-10">
                        @Html.DropDownList("dest", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.dest, "", new { @class = "text-danger" })
                    <br />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2">Date of Journey: </label>
                    <div class="col-md-10">
                        <input type="date" name="dateOfJourney" class="form-control"/>
                        @Html.ValidationMessageFor(model => model.scheduleDate, "")
                        <br />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="submit" />
                    </div>
                </div>
            </fieldset>
        }

    </div>
    <div class="col-md-4">
        @Html.ActionLink("Booking Hisory","Index","Reservations")<br/><br/>

        <img src="~/Content/birdsdoitpas.jpg" height="200" width="500">

    </div>
</div>

FlightReservationSystem/Views/Home/SearchResults.cshtml
@model IEnumerable<FlightReservationSystem.Models.Schedule>

@{
    ViewBag.Title = "SearchResults";
}

<h2>SearchResults</h2>
<br/>
@ViewBag.ScheduleMessage
<br/>
<h4>Source : @ViewBag.Source | Destination: @ViewBag.Dest </h4><br/>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Flight.flightName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.scheduleDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.depatureTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.arrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.arrivalTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th>
            (First class) Available Seats | Cost
        </th>
        <th>
            (Business class) Available Seats | Cost        
        </th>
        <th>
            (Economy class) Available Seats | Cost
        </th>
        <th>
            @Html.DisplayNameFor(model => model.traveltype)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Flight.flightName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.scheduleDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.depatureTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.arrivalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.arrivalTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FCseats) | 
            @Html.DisplayFor(modelItem => item.costFirst) | 
            @if (! item.scheduleDate.ToShortDateString().Contains(DateTime.Today.ToShortDateString()))
            {
                if (item.FCseats > 0)
                {
                    using (Html.BeginForm("Book", "Reservations", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("sid", item.scheduleId)
                        @Html.Hidden("fid", item.flightId)
                        @Html.Hidden("doj", item.scheduleDate)
                        @Html.Hidden("name", item.Flight.flightName)
                        @Html.Hidden("Tclass", "First")
                    <input type="submit" value="Book" class="btn"/>
                    }

                }
            }
            else
            {
                <div>cannot book!!</div>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BCseats) | 
            @Html.DisplayFor(modelItem => item.costBusiness) | 
            @if (!item.scheduleDate.ToShortDateString().Contains(DateTime.Today.ToShortDateString()))
            {
                if (item.BCseats > 0)
                {
                    using (Html.BeginForm("Book", "Reservations", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("sid", item.scheduleId)
                        @Html.Hidden("fid", item.flightId)
                        @Html.Hidden("doj", item.scheduleDate)
                        @Html.Hidden("name", item.Flight.flightName)
                        @Html.Hidden("Tclass", "Business")
                        <input type="submit" value="Book" class="btn" />
                    }

                }
            }
            else
            {
                <div>cannot book!!</div>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ECseats) | 
            @Html.DisplayFor(modelItem => item.costEconomy) | 
            @if (!item.scheduleDate.ToShortDateString().Contains(DateTime.Today.ToShortDateString()))
            {
                if (item.ECseats > 0)
                {
                    using (Html.BeginForm("Book", "Reservations", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("sid", item.scheduleId)
                        @Html.Hidden("fid", item.flightId)
                        @Html.Hidden("doj", item.scheduleDate)
                        @Html.Hidden("name", item.Flight.flightName)
                        @Html.Hidden("Tclass", "Economy")
                        <input type="submit" value="Book" class="btn" />
                    }

                }
            }
            else
            {
                <div>cannot book!!</div>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.traveltype)
        </td>
        @*<td>
        @Html.ActionLink("Book", "Book", "Reservations", new { sid = item.scheduleId, fid = item.flightId, doj = item.scheduleDate, name = item.Flight.flightName }, null) }   
        </td>*@
    </tr>
}

</table>